<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <PackOnBuild>true</PackOnBuild>
    <GeneratePackageOnBuild>$(PackOnBuild)</GeneratePackageOnBuild>
    <PackageId>MediaPipeTasksGenAI.iOS</PackageId>
    <PackageVersion>0.10.35</PackageVersion>
    <Authors>Howard Good</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Owners>https://www.nuget.org/profiles/v-hogood</Owners>
    <RepositoryUrl>https://github.com/google/mediapipe</RepositoryUrl>
    <PackageProjectUrl>https://github.com/v-hogood/MediaPipeTasks</PackageProjectUrl>
    <Summary>iOS .NET bindings for MediaPipe Tasks GenAI Library.</Summary>
    <PackageTags>maui xamarin ios mediapipe</PackageTags>
    <Title>MediaPipeTasksGenAI</Title>
    <Description>.NET iOS bindings for MediaPipe Tasks GenAI Library.</Description>
    <NoWarn>NU5123</NoWarn>
    <LinkWithSwiftSystemLibraries>true</LinkWithSwiftSystemLibraries>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
    <None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="frameworks/MediaPipeTasksGenAI.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>False</SmartLink>
      <LinkerFlags>-ObjC</LinkerFlags>
    </NativeReference>
    <NativeReference Include="MediaPipeTasksGenAIProxy/MediaPipeTasksGenAIProxy.xcframework">
      <Kind>Static</Kind>
      <SmartLink>False</SmartLink>
      <ForceLoad>True</ForceLoad>
      <LinkerFlags>-ObjC</LinkerFlags>
    </NativeReference>
    <NativeReference Include="frameworks/MediaPipeTasksGenAIC.xcframework">
      <Kind>Static</Kind>
      <SmartLink>False</SmartLink>
      <ForceLoad>True</ForceLoad>
      <LinkerFlags>-ObjC</LinkerFlags>
      <Frameworks>Accelerate CoreVideo Metal OpenGLES</Frameworks>
    </NativeReference>
  </ItemGroup>
  <ItemGroup>
    <None Remove="frameworks/**/*" />
    <None Remove="MediaPipeTasksGenAIProxy/**/*" />
  </ItemGroup>
  <Target Name="DownloadFile" BeforeTargets="BeforeBuild">
    <DownloadFile SourceUrl="https://dl.google.com/cpdc/20260427-204215/MediaPipeTasksGenAI-0.10.35.tar.gz" DestinationFolder="." />
    <Exec Command="tar -xf MediaPipeTasksGenAI-0.10.35.tar.gz" />
    <DownloadFile SourceUrl="https://dl.google.com/cpdc/20260427-204219/MediaPipeTasksGenAIC-0.10.35.tar.gz" DestinationFolder="." />
    <Exec Command="tar -xf MediaPipeTasksGenAIC-0.10.35.tar.gz" />
    <RemoveDir Directories="MediaPipeTasksGenAIProxy/MediaPipeTasksGenAIProxy.xcframework" />
    <Exec Command="xcodebuild archive -scheme MediaPipeTasksGenAIProxy -archivePath iphoneos.xcarchive -sdk iphoneos" WorkingDirectory="./MediaPipeTasksGenAIProxy" />
    <Exec Command="xcodebuild archive -scheme MediaPipeTasksGenAIProxy -archivePath iphonesimulator.xcarchive -sdk iphonesimulator" WorkingDirectory="./MediaPipeTasksGenAIProxy" />
    <Exec Command="xcodebuild -create-xcframework -archive iphoneos.xcarchive -framework MediaPipeTasksGenAIProxy.framework -archive iphonesimulator.xcarchive -framework MediaPipeTasksGenAIProxy.framework -output MediaPipeTasksGenAIProxy.xcframework" WorkingDirectory="./MediaPipeTasksGenAIProxy" />
  </Target>
</Project>
